---
version: "2.0"

endpoints:
  myendpoint:
    kind: ip

services:
  service-1:
    image: slickci/slickci-runner:1.0.0
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
            ip: "myendpoint"

profiles:
  compute:
    service-1:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          - size: 100Mi
  placement:
    dcloud:
      pricing:
        service-1:
          denom: uakt
          amount: 1000

deployment:
  service-1:
    dcloud:
      profile: service-1
      count: 1
